### ISSUE TITLE
在主题目录运行 make assets报错，无法生成css文件（mac os）

### ISSUE THREAD

**Issue by bitepeng** [GoAdminGroup/themes#1]
在主题目录运行 make assets报错，无法生成css文件（mac os）
 
do The Minifying Error : unexpected ending in qualified rule, expected left brace token

**Comment by chenhg5** [comment]
@bitepeng 可以提供下修改的css内容吗

**Comment by bitepeng** [comment]
`.btn-file::-ms-browse {
    width:100%;
    height:100%
}
owed}.file-sortable .file-drag-handle {
         cursor:move;
         cursor:-webkit-grabbing;
         opacity:1
     }`

问题找到了，代码库里的b_fileinput.min.css文件中存在多余的字符 

> owed}
